### ISSUE TITLE
[03_타입과_추상화] 객체를 적절한 개념에 따라 분류할때의 이점

### ISSUE THREAD

**Issue by luminoustone** [MiracleCrew/Object-Orientation_facts_and_misconceptions#1]
- purpose: 설명 및 예시
- page: p.87(아래 문단)

## 설명
> 반면에 객체를 적절한 개념에 따라 분류한 애플리케이션은 유지보수가 용이하고 변경에 유연하게 대처할 수 있다.

위에 문장에서 어떤식으로 유지보수와 변경에 유리해지는지 예시와 함께 설명해주세요..

**Comment by eomseonmi** [comment]
![image](https://github.com/MiracleCrew/Object-Orientation_facts_and_misconceptions/assets/11703564/adb7a8df-0a43-44de-8e6c-5e5f7a87e1d2)


[어떤식으로 유지보수가 유리 해지는지?]
객체를 공통점을 기반으로 잘 묶어 분류하게 되면
(☞ 적절한 개념에 따라 분류하게 되면)
위에 이미지에서 새로운 oPet / oHuman 을 생성하기가 매우 쉽고 용이하다.
oPet / oHuman 을 확장하여 유지보수가 가능하기 때문이다.


[어떤식으로 변경에 유리 해지는지?]
공통적인 사항이 변경된다고 하면,
예를 들면 oPet에 무게라는 상태를 추가한다고 하자!
그러면 oPet에 무게라는 상태를 추가하면 oDog 과 oCat 도 무게라는 상태를 사용할  수 있다.

무게에 따라 작은 pet 과 큰 pet으로 나눠야하는 변경사항이 발생했을때도
무게라는 상태를 oPet에 추가하여 변경사항을 유연하게 대체 할수도 있다.

**Comment by luminoustone** [comment]
적절한 예시 감사합니다!!!! 이해 잘 된거같습니다!!
